### ISSUE TITLE
No error is shown to the user during the signup process.

### ISSUE THREAD

**Issue by mustafa-shahriar** [Hasnathasan/Cholo_Bazar_client_side#2]
In Sign up process there is no way for a user to know when an error occurs because when an error occurs the error is being printed only. I think it would be better to notify the user using Swal when an error occurs during Sing up process.

![Screenshot (107)](https://github.com/Hasnathasan/Cholo_Bazar_client_side/assets/112774475/b0af2e6e-5e33-45d4-8c6d-20c35535edd7)

**Comment by Hasnathasan** [comment]
The project isn't completed yet. I am still working on this project. There are so many bugs and I am improving them regularly. I will add more features.

By the way, thanks for letting me know about the issue. I will solve that as soon as possible.
